[package]
name = "reclaw-ui"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
freya = { version = "=0.5.0-rc.8", features = ["router"] }
freya-icons = { version = "=0.5.0-rc.8", features = ["lucide"] }
bytes = "1"

[dev-dependencies]
freya-testing = "=0.5.0-rc.8"
freya-core = "=0.5.0-rc.8"
